### ISSUE TITLE
The Covid-19 Data not showing 

### ISSUE THREAD

**Issue by Ritik-creator** [marlon360/covid-ar#1]
Hello

First of all , i love this project 

Well the problem here i facing is that while running its not showing any chart/data of Covid-19, only just the Map 

I will be very grateful if u fix this 

Danke !!

**Comment by marlon360** [comment]
Hello!

Unfortunately the old API is not working anymore. I updated the Unity project with a new API. 
If you want to use it now, you have to download the Unity Project and build the APK yourself.

I will release a new version with the new API shortly.

**Comment by marlon360** [comment]
I updated the release!

@Ritik-creator Download the APK from this release: https://github.com/marlon360/covid-ar/releases/tag/v1.1.0
